/**
 * This script removes the broken auto-generated page-specific CSS files
 * and replaces their imports in JSX files with nothing (since style.css 
 * is already loaded globally via index.html).
 * 
 * The per-page CSS files were generated by a faulty conversion script and 
 * contain broken selectors like ".neet-page /* comment * / .section-title"
 * and bare "* { margin: 0; padding: 0; }" that completely breaks Bootstrap grid.
 */

const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, 'src', 'pages');

// CSS files we want to KEEP (they have hand-written content)
const keepFiles = new Set([
  'Gallery.css',
  'BlogPostView.css',
]);

function processDir(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      processDir(fullPath);
      continue;
    }
    
    // Delete broken CSS files
    if (file.endsWith('.css') && !keepFiles.has(file)) {
      fs.unlinkSync(fullPath);
      console.log(`Deleted broken CSS: ${file}`);
    }
    
    // Remove the CSS import from JSX files 
    if (file.endsWith('.jsx')) {
      let content = fs.readFileSync(fullPath, 'utf-8');
      const cssName = file.replace('.jsx', '.css');
      
      if (!keepFiles.has(cssName)) {
        // Remove import './PageName.css'; lines
        const importRegex = new RegExp(`import\\s+['\"]\\.\\/` + cssName.replace('.', '\\.') + `['\"];?\\s*\\n?`, 'g');
        const newContent = content.replace(importRegex, '');
        if (newContent !== content) {
          fs.writeFileSync(fullPath, newContent);
          console.log(`Removed CSS import from: ${file}`);
        }
      }
    }
  }
}

processDir(pagesDir);
console.log('\nDone. All broken page CSS files removed.');
console.log('Global styles from /assets/styles/style.css (loaded in index.html) will handle all styling.');
